// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _01_ASP_MVC_Shop.Data;

#nullable disable

namespace _01_ASP_MVC_Shop.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260211101223_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("_01_ASP_MVC_Shop.Models.CategoryModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Ноутбуки"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Настільні ПК"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Монітори"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Відеокарти"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Процесори"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Материнські плати"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Оперативна пам’ять"
                        },
                        new
                        {
                            Id = 8,
                            Name = "SSD накопичувачі"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Периферія"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Мережеве обладнання"
                        });
                });

            modelBuilder.Entity("_01_ASP_MVC_Shop.Models.ProductModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "ASUS",
                            CategoryId = 1,
                            Name = "ROG Strix G16",
                            Price = 58999m
                        },
                        new
                        {
                            Id = 2,
                            Brand = "ASUS",
                            CategoryId = 1,
                            Name = "TUF Gaming A15",
                            Price = 36999m
                        },
                        new
                        {
                            Id = 3,
                            Brand = "ASUS",
                            CategoryId = 1,
                            Name = "ZenBook 14",
                            Price = 38999m
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Apple",
                            CategoryId = 1,
                            Name = "MacBook Air M2",
                            Price = 45999m
                        },
                        new
                        {
                            Id = 5,
                            Brand = "Apple",
                            CategoryId = 1,
                            Name = "MacBook Pro 14 M3",
                            Price = 89999m
                        },
                        new
                        {
                            Id = 6,
                            Brand = "Lenovo",
                            CategoryId = 1,
                            Name = "ThinkPad X13",
                            Price = 39999m
                        },
                        new
                        {
                            Id = 7,
                            Brand = "Lenovo",
                            CategoryId = 1,
                            Name = "Legion 5 Pro",
                            Price = 54999m
                        },
                        new
                        {
                            Id = 8,
                            Brand = "Lenovo",
                            CategoryId = 1,
                            Name = "IdeaPad 5",
                            Price = 21999m
                        },
                        new
                        {
                            Id = 9,
                            Brand = "HP",
                            CategoryId = 1,
                            Name = "HP Pavilion 15",
                            Price = 27999m
                        },
                        new
                        {
                            Id = 10,
                            Brand = "HP",
                            CategoryId = 1,
                            Name = "HP Omen 16",
                            Price = 62999m
                        },
                        new
                        {
                            Id = 11,
                            Brand = "Acer",
                            CategoryId = 1,
                            Name = "Acer Nitro 5",
                            Price = 32999m
                        },
                        new
                        {
                            Id = 12,
                            Brand = "Acer",
                            CategoryId = 1,
                            Name = "Acer Swift 3",
                            Price = 23999m
                        },
                        new
                        {
                            Id = 13,
                            Brand = "Dell",
                            CategoryId = 1,
                            Name = "Dell XPS 13",
                            Price = 54999m
                        },
                        new
                        {
                            Id = 14,
                            Brand = "Dell",
                            CategoryId = 1,
                            Name = "Dell Inspiron 14",
                            Price = 28999m
                        },
                        new
                        {
                            Id = 15,
                            Brand = "MSI",
                            CategoryId = 1,
                            Name = "MSI Katana 15",
                            Price = 41999m
                        },
                        new
                        {
                            Id = 16,
                            Brand = "MSI",
                            CategoryId = 1,
                            Name = "MSI Stealth 16",
                            Price = 72999m
                        },
                        new
                        {
                            Id = 17,
                            Brand = "Gigabyte",
                            CategoryId = 1,
                            Name = "Gigabyte G5",
                            Price = 33999m
                        },
                        new
                        {
                            Id = 18,
                            Brand = "Huawei",
                            CategoryId = 1,
                            Name = "Huawei MateBook D15",
                            Price = 25999m
                        },
                        new
                        {
                            Id = 19,
                            Brand = "Samsung",
                            CategoryId = 1,
                            Name = "Samsung Galaxy Book3",
                            Price = 34999m
                        },
                        new
                        {
                            Id = 20,
                            Brand = "Razer",
                            CategoryId = 1,
                            Name = "Razer Blade 15",
                            Price = 79999m
                        },
                        new
                        {
                            Id = 21,
                            Brand = "ASUS",
                            CategoryId = 2,
                            Name = "ROG Strix GT15",
                            Price = 65999m
                        },
                        new
                        {
                            Id = 22,
                            Brand = "HP",
                            CategoryId = 2,
                            Name = "HP Omen 45L",
                            Price = 89999m
                        },
                        new
                        {
                            Id = 23,
                            Brand = "Acer",
                            CategoryId = 2,
                            Name = "Acer Predator Orion 3000",
                            Price = 72999m
                        },
                        new
                        {
                            Id = 24,
                            Brand = "Lenovo",
                            CategoryId = 2,
                            Name = "Lenovo Legion Tower 5",
                            Price = 68999m
                        },
                        new
                        {
                            Id = 25,
                            Brand = "Dell",
                            CategoryId = 2,
                            Name = "Alienware Aurora R15",
                            Price = 119999m
                        },
                        new
                        {
                            Id = 26,
                            Brand = "MSI",
                            CategoryId = 2,
                            Name = "MSI Infinite X2",
                            Price = 94999m
                        },
                        new
                        {
                            Id = 27,
                            Brand = "Apple",
                            CategoryId = 2,
                            Name = "Mac Studio M2",
                            Price = 99999m
                        },
                        new
                        {
                            Id = 28,
                            Brand = "Apple",
                            CategoryId = 2,
                            Name = "Mac Mini M2",
                            Price = 29999m
                        },
                        new
                        {
                            Id = 29,
                            Brand = "ASUS",
                            CategoryId = 2,
                            Name = "ExpertCenter D5",
                            Price = 25999m
                        },
                        new
                        {
                            Id = 30,
                            Brand = "HP",
                            CategoryId = 2,
                            Name = "ProDesk 400",
                            Price = 21999m
                        },
                        new
                        {
                            Id = 31,
                            Brand = "Lenovo",
                            CategoryId = 2,
                            Name = "ThinkCentre M70",
                            Price = 23999m
                        },
                        new
                        {
                            Id = 32,
                            Brand = "Dell",
                            CategoryId = 2,
                            Name = "OptiPlex 7000",
                            Price = 28999m
                        },
                        new
                        {
                            Id = 33,
                            Brand = "Acer",
                            CategoryId = 2,
                            Name = "Aspire TC",
                            Price = 19999m
                        },
                        new
                        {
                            Id = 34,
                            Brand = "Gigabyte",
                            CategoryId = 2,
                            Name = "AORUS Model X",
                            Price = 109999m
                        },
                        new
                        {
                            Id = 35,
                            Brand = "MSI",
                            CategoryId = 2,
                            Name = "Trident 3",
                            Price = 49999m
                        },
                        new
                        {
                            Id = 36,
                            Brand = "HP",
                            CategoryId = 2,
                            Name = "Pavilion Gaming TG01",
                            Price = 37999m
                        },
                        new
                        {
                            Id = 37,
                            Brand = "Lenovo",
                            CategoryId = 2,
                            Name = "IdeaCentre 5",
                            Price = 31999m
                        },
                        new
                        {
                            Id = 38,
                            Brand = "Dell",
                            CategoryId = 2,
                            Name = "Vostro 3910",
                            Price = 26999m
                        },
                        new
                        {
                            Id = 39,
                            Brand = "ASUS",
                            CategoryId = 2,
                            Name = "ROG G22CH",
                            Price = 74999m
                        },
                        new
                        {
                            Id = 40,
                            Brand = "Acer",
                            CategoryId = 2,
                            Name = "Veriton X",
                            Price = 22999m
                        },
                        new
                        {
                            Id = 41,
                            Brand = "Samsung",
                            CategoryId = 3,
                            Name = "Odyssey G7 27",
                            Price = 18999m
                        },
                        new
                        {
                            Id = 42,
                            Brand = "LG",
                            CategoryId = 3,
                            Name = "UltraGear 27GP850",
                            Price = 17999m
                        },
                        new
                        {
                            Id = 43,
                            Brand = "ASUS",
                            CategoryId = 3,
                            Name = "TUF VG27AQ",
                            Price = 16999m
                        },
                        new
                        {
                            Id = 44,
                            Brand = "Acer",
                            CategoryId = 3,
                            Name = "Predator XB273",
                            Price = 19999m
                        },
                        new
                        {
                            Id = 45,
                            Brand = "Dell",
                            CategoryId = 3,
                            Name = "Dell S2721DGF",
                            Price = 15999m
                        },
                        new
                        {
                            Id = 46,
                            Brand = "AOC",
                            CategoryId = 3,
                            Name = "AOC CQ27G2",
                            Price = 12999m
                        },
                        new
                        {
                            Id = 47,
                            Brand = "MSI",
                            CategoryId = 3,
                            Name = "MSI Optix MAG274",
                            Price = 14999m
                        },
                        new
                        {
                            Id = 48,
                            Brand = "Gigabyte",
                            CategoryId = 3,
                            Name = "Gigabyte M27Q",
                            Price = 13999m
                        },
                        new
                        {
                            Id = 49,
                            Brand = "Philips",
                            CategoryId = 3,
                            Name = "Philips 272E1CA",
                            Price = 9999m
                        },
                        new
                        {
                            Id = 50,
                            Brand = "ViewSonic",
                            CategoryId = 3,
                            Name = "ViewSonic XG2405",
                            Price = 10999m
                        },
                        new
                        {
                            Id = 51,
                            Brand = "BenQ",
                            CategoryId = 3,
                            Name = "BenQ EX2780Q",
                            Price = 14999m
                        },
                        new
                        {
                            Id = 52,
                            Brand = "LG",
                            CategoryId = 3,
                            Name = "LG 34GN850",
                            Price = 29999m
                        },
                        new
                        {
                            Id = 53,
                            Brand = "Samsung",
                            CategoryId = 3,
                            Name = "Samsung S80UA",
                            Price = 21999m
                        },
                        new
                        {
                            Id = 54,
                            Brand = "ASUS",
                            CategoryId = 3,
                            Name = "ASUS ProArt PA32",
                            Price = 45999m
                        },
                        new
                        {
                            Id = 55,
                            Brand = "Dell",
                            CategoryId = 3,
                            Name = "Dell P2422H",
                            Price = 8999m
                        },
                        new
                        {
                            Id = 56,
                            Brand = "Acer",
                            CategoryId = 3,
                            Name = "Acer CB242Y",
                            Price = 7999m
                        },
                        new
                        {
                            Id = 57,
                            Brand = "HP",
                            CategoryId = 3,
                            Name = "HP X27",
                            Price = 11999m
                        },
                        new
                        {
                            Id = 58,
                            Brand = "Lenovo",
                            CategoryId = 3,
                            Name = "Lenovo G27q-30",
                            Price = 10999m
                        },
                        new
                        {
                            Id = 59,
                            Brand = "MSI",
                            CategoryId = 3,
                            Name = "MSI MPG341",
                            Price = 32999m
                        },
                        new
                        {
                            Id = 60,
                            Brand = "Gigabyte",
                            CategoryId = 3,
                            Name = "Gigabyte G32QC",
                            Price = 18999m
                        },
                        new
                        {
                            Id = 61,
                            Brand = "Gigabyte",
                            CategoryId = 4,
                            Name = "RTX 4090 Gaming OC",
                            Price = 89999m
                        },
                        new
                        {
                            Id = 62,
                            Brand = "ASUS",
                            CategoryId = 4,
                            Name = "RTX 4080 Super",
                            Price = 59999m
                        },
                        new
                        {
                            Id = 63,
                            Brand = "MSI",
                            CategoryId = 4,
                            Name = "RTX 4070 Ti",
                            Price = 44999m
                        },
                        new
                        {
                            Id = 64,
                            Brand = "Gigabyte",
                            CategoryId = 4,
                            Name = "RTX 4070",
                            Price = 35999m
                        },
                        new
                        {
                            Id = 65,
                            Brand = "ASUS",
                            CategoryId = 4,
                            Name = "RTX 4060 Ti",
                            Price = 25999m
                        },
                        new
                        {
                            Id = 66,
                            Brand = "MSI",
                            CategoryId = 4,
                            Name = "RTX 4060",
                            Price = 19999m
                        },
                        new
                        {
                            Id = 67,
                            Brand = "Sapphire",
                            CategoryId = 4,
                            Name = "RX 7900 XTX",
                            Price = 54999m
                        },
                        new
                        {
                            Id = 68,
                            Brand = "Sapphire",
                            CategoryId = 4,
                            Name = "RX 7900 XT",
                            Price = 47999m
                        },
                        new
                        {
                            Id = 69,
                            Brand = "Gigabyte",
                            CategoryId = 4,
                            Name = "RX 7800 XT",
                            Price = 32999m
                        },
                        new
                        {
                            Id = 70,
                            Brand = "ASRock",
                            CategoryId = 4,
                            Name = "RX 7700 XT",
                            Price = 28999m
                        },
                        new
                        {
                            Id = 71,
                            Brand = "MSI",
                            CategoryId = 4,
                            Name = "RTX 3060",
                            Price = 14999m
                        },
                        new
                        {
                            Id = 72,
                            Brand = "ASUS",
                            CategoryId = 4,
                            Name = "RTX 3050",
                            Price = 10999m
                        },
                        new
                        {
                            Id = 73,
                            Brand = "Sapphire",
                            CategoryId = 4,
                            Name = "RX 6600",
                            Price = 11999m
                        },
                        new
                        {
                            Id = 74,
                            Brand = "Gigabyte",
                            CategoryId = 4,
                            Name = "RX 6500 XT",
                            Price = 8999m
                        },
                        new
                        {
                            Id = 75,
                            Brand = "ASUS",
                            CategoryId = 4,
                            Name = "RTX 3080 Ti",
                            Price = 34999m
                        },
                        new
                        {
                            Id = 76,
                            Brand = "MSI",
                            CategoryId = 4,
                            Name = "RTX 3090",
                            Price = 39999m
                        },
                        new
                        {
                            Id = 77,
                            Brand = "Sapphire",
                            CategoryId = 4,
                            Name = "RX 6800 XT",
                            Price = 25999m
                        },
                        new
                        {
                            Id = 78,
                            Brand = "Gigabyte",
                            CategoryId = 4,
                            Name = "RX 6700 XT",
                            Price = 19999m
                        },
                        new
                        {
                            Id = 79,
                            Brand = "ASUS",
                            CategoryId = 4,
                            Name = "RTX 3070",
                            Price = 17999m
                        },
                        new
                        {
                            Id = 80,
                            Brand = "MSI",
                            CategoryId = 4,
                            Name = "RTX 2060",
                            Price = 8999m
                        },
                        new
                        {
                            Id = 81,
                            Brand = "AMD",
                            CategoryId = 5,
                            Name = "Ryzen 9 7950X",
                            Price = 25999m
                        },
                        new
                        {
                            Id = 82,
                            Brand = "AMD",
                            CategoryId = 5,
                            Name = "Ryzen 7 7800X3D",
                            Price = 18999m
                        },
                        new
                        {
                            Id = 83,
                            Brand = "AMD",
                            CategoryId = 5,
                            Name = "Ryzen 5 7600X",
                            Price = 9999m
                        },
                        new
                        {
                            Id = 84,
                            Brand = "AMD",
                            CategoryId = 5,
                            Name = "Ryzen 7 5800X",
                            Price = 8999m
                        },
                        new
                        {
                            Id = 85,
                            Brand = "AMD",
                            CategoryId = 5,
                            Name = "Ryzen 5 5600X",
                            Price = 6999m
                        },
                        new
                        {
                            Id = 86,
                            Brand = "Intel",
                            CategoryId = 5,
                            Name = "Core i9-14900K",
                            Price = 27999m
                        },
                        new
                        {
                            Id = 87,
                            Brand = "Intel",
                            CategoryId = 5,
                            Name = "Core i7-14700K",
                            Price = 18999m
                        },
                        new
                        {
                            Id = 88,
                            Brand = "Intel",
                            CategoryId = 5,
                            Name = "Core i5-14600K",
                            Price = 11999m
                        },
                        new
                        {
                            Id = 89,
                            Brand = "Intel",
                            CategoryId = 5,
                            Name = "Core i7-13700K",
                            Price = 16999m
                        },
                        new
                        {
                            Id = 90,
                            Brand = "Intel",
                            CategoryId = 5,
                            Name = "Core i5-13600K",
                            Price = 10999m
                        },
                        new
                        {
                            Id = 91,
                            Brand = "AMD",
                            CategoryId = 5,
                            Name = "Ryzen 9 5900X",
                            Price = 13999m
                        },
                        new
                        {
                            Id = 92,
                            Brand = "AMD",
                            CategoryId = 5,
                            Name = "Ryzen 5 5500",
                            Price = 4999m
                        },
                        new
                        {
                            Id = 93,
                            Brand = "Intel",
                            CategoryId = 5,
                            Name = "Core i3-13100",
                            Price = 4999m
                        },
                        new
                        {
                            Id = 94,
                            Brand = "Intel",
                            CategoryId = 5,
                            Name = "Core i9-13900K",
                            Price = 23999m
                        },
                        new
                        {
                            Id = 95,
                            Brand = "AMD",
                            CategoryId = 5,
                            Name = "Ryzen 7 7700X",
                            Price = 14999m
                        },
                        new
                        {
                            Id = 96,
                            Brand = "Intel",
                            CategoryId = 5,
                            Name = "Core i5-12400F",
                            Price = 5999m
                        },
                        new
                        {
                            Id = 97,
                            Brand = "AMD",
                            CategoryId = 5,
                            Name = "Ryzen 3 4100",
                            Price = 2999m
                        },
                        new
                        {
                            Id = 98,
                            Brand = "Intel",
                            CategoryId = 5,
                            Name = "Core i7-12700K",
                            Price = 13999m
                        },
                        new
                        {
                            Id = 99,
                            Brand = "AMD",
                            CategoryId = 5,
                            Name = "Ryzen 9 7900X",
                            Price = 20999m
                        },
                        new
                        {
                            Id = 100,
                            Brand = "Intel",
                            CategoryId = 5,
                            Name = "Core i5-13400",
                            Price = 7999m
                        },
                        new
                        {
                            Id = 101,
                            Brand = "ASUS",
                            CategoryId = 6,
                            Name = "ROG Strix Z790-E",
                            Price = 18999m
                        },
                        new
                        {
                            Id = 102,
                            Brand = "ASUS",
                            CategoryId = 6,
                            Name = "TUF B650-Plus",
                            Price = 7999m
                        },
                        new
                        {
                            Id = 103,
                            Brand = "MSI",
                            CategoryId = 6,
                            Name = "MSI MPG Z790 Carbon",
                            Price = 17999m
                        },
                        new
                        {
                            Id = 104,
                            Brand = "MSI",
                            CategoryId = 6,
                            Name = "MSI B550 Tomahawk",
                            Price = 5999m
                        },
                        new
                        {
                            Id = 105,
                            Brand = "Gigabyte",
                            CategoryId = 6,
                            Name = "Gigabyte Z790 Aorus Elite",
                            Price = 14999m
                        },
                        new
                        {
                            Id = 106,
                            Brand = "Gigabyte",
                            CategoryId = 6,
                            Name = "Gigabyte B650 Aorus",
                            Price = 8999m
                        },
                        new
                        {
                            Id = 107,
                            Brand = "ASRock",
                            CategoryId = 6,
                            Name = "ASRock Z790 Steel Legend",
                            Price = 12999m
                        },
                        new
                        {
                            Id = 108,
                            Brand = "ASRock",
                            CategoryId = 6,
                            Name = "ASRock B550M Pro4",
                            Price = 4999m
                        },
                        new
                        {
                            Id = 109,
                            Brand = "ASUS",
                            CategoryId = 6,
                            Name = "ASUS Prime H610M",
                            Price = 3999m
                        },
                        new
                        {
                            Id = 110,
                            Brand = "MSI",
                            CategoryId = 6,
                            Name = "MSI PRO B760M",
                            Price = 4999m
                        },
                        new
                        {
                            Id = 111,
                            Brand = "Gigabyte",
                            CategoryId = 6,
                            Name = "Gigabyte H610M S2H",
                            Price = 3499m
                        },
                        new
                        {
                            Id = 112,
                            Brand = "ASRock",
                            CategoryId = 6,
                            Name = "ASRock B650M PG",
                            Price = 6999m
                        },
                        new
                        {
                            Id = 113,
                            Brand = "ASUS",
                            CategoryId = 6,
                            Name = "ROG Crosshair X670E",
                            Price = 23999m
                        },
                        new
                        {
                            Id = 114,
                            Brand = "MSI",
                            CategoryId = 6,
                            Name = "MSI MEG Z790 ACE",
                            Price = 25999m
                        },
                        new
                        {
                            Id = 115,
                            Brand = "Gigabyte",
                            CategoryId = 6,
                            Name = "Gigabyte X670 Aorus Master",
                            Price = 21999m
                        },
                        new
                        {
                            Id = 116,
                            Brand = "ASRock",
                            CategoryId = 6,
                            Name = "ASRock X570 Taichi",
                            Price = 11999m
                        },
                        new
                        {
                            Id = 117,
                            Brand = "ASUS",
                            CategoryId = 6,
                            Name = "ASUS Prime B550M-A",
                            Price = 4499m
                        },
                        new
                        {
                            Id = 118,
                            Brand = "MSI",
                            CategoryId = 6,
                            Name = "MSI B450 Tomahawk",
                            Price = 3999m
                        },
                        new
                        {
                            Id = 119,
                            Brand = "Gigabyte",
                            CategoryId = 6,
                            Name = "Gigabyte B760 Gaming X",
                            Price = 8999m
                        },
                        new
                        {
                            Id = 120,
                            Brand = "ASRock",
                            CategoryId = 6,
                            Name = "ASRock H610M-HDV",
                            Price = 2999m
                        },
                        new
                        {
                            Id = 121,
                            Brand = "Kingston",
                            CategoryId = 7,
                            Name = "Kingston Fury 16GB DDR5",
                            Price = 3499m
                        },
                        new
                        {
                            Id = 122,
                            Brand = "Kingston",
                            CategoryId = 7,
                            Name = "Kingston Fury 32GB DDR5",
                            Price = 6999m
                        },
                        new
                        {
                            Id = 123,
                            Brand = "Corsair",
                            CategoryId = 7,
                            Name = "Corsair Vengeance 16GB DDR4",
                            Price = 2499m
                        },
                        new
                        {
                            Id = 124,
                            Brand = "Corsair",
                            CategoryId = 7,
                            Name = "Corsair Vengeance 32GB DDR4",
                            Price = 4999m
                        },
                        new
                        {
                            Id = 125,
                            Brand = "G.Skill",
                            CategoryId = 7,
                            Name = "G.Skill Trident Z 16GB",
                            Price = 2999m
                        },
                        new
                        {
                            Id = 126,
                            Brand = "G.Skill",
                            CategoryId = 7,
                            Name = "G.Skill Trident Z 32GB",
                            Price = 5999m
                        },
                        new
                        {
                            Id = 127,
                            Brand = "HyperX",
                            CategoryId = 7,
                            Name = "HyperX Fury 16GB",
                            Price = 2399m
                        },
                        new
                        {
                            Id = 128,
                            Brand = "HyperX",
                            CategoryId = 7,
                            Name = "HyperX Fury 32GB",
                            Price = 4799m
                        },
                        new
                        {
                            Id = 129,
                            Brand = "TeamGroup",
                            CategoryId = 7,
                            Name = "TeamGroup T-Force 16GB",
                            Price = 2199m
                        },
                        new
                        {
                            Id = 130,
                            Brand = "TeamGroup",
                            CategoryId = 7,
                            Name = "TeamGroup T-Force 32GB",
                            Price = 4299m
                        },
                        new
                        {
                            Id = 131,
                            Brand = "Patriot",
                            CategoryId = 7,
                            Name = "Patriot Viper 16GB",
                            Price = 1999m
                        },
                        new
                        {
                            Id = 132,
                            Brand = "Patriot",
                            CategoryId = 7,
                            Name = "Patriot Viper 32GB",
                            Price = 3999m
                        },
                        new
                        {
                            Id = 133,
                            Brand = "ADATA",
                            CategoryId = 7,
                            Name = "ADATA XPG 16GB",
                            Price = 2299m
                        },
                        new
                        {
                            Id = 134,
                            Brand = "ADATA",
                            CategoryId = 7,
                            Name = "ADATA XPG 32GB",
                            Price = 4599m
                        },
                        new
                        {
                            Id = 135,
                            Brand = "Crucial",
                            CategoryId = 7,
                            Name = "Crucial 16GB DDR4",
                            Price = 1999m
                        },
                        new
                        {
                            Id = 136,
                            Brand = "Crucial",
                            CategoryId = 7,
                            Name = "Crucial 32GB DDR4",
                            Price = 3999m
                        },
                        new
                        {
                            Id = 137,
                            Brand = "Kingston",
                            CategoryId = 7,
                            Name = "Kingston ValueRAM 8GB",
                            Price = 999m
                        },
                        new
                        {
                            Id = 138,
                            Brand = "Corsair",
                            CategoryId = 7,
                            Name = "Corsair Dominator 32GB",
                            Price = 7999m
                        },
                        new
                        {
                            Id = 139,
                            Brand = "G.Skill",
                            CategoryId = 7,
                            Name = "G.Skill Ripjaws 16GB",
                            Price = 2499m
                        },
                        new
                        {
                            Id = 140,
                            Brand = "HyperX",
                            CategoryId = 7,
                            Name = "HyperX Impact 16GB",
                            Price = 2699m
                        },
                        new
                        {
                            Id = 141,
                            Brand = "Samsung",
                            CategoryId = 8,
                            Name = "Samsung 990 Pro 1TB",
                            Price = 4999m
                        },
                        new
                        {
                            Id = 142,
                            Brand = "Samsung",
                            CategoryId = 8,
                            Name = "Samsung 980 Pro 2TB",
                            Price = 7999m
                        },
                        new
                        {
                            Id = 143,
                            Brand = "WD",
                            CategoryId = 8,
                            Name = "WD Black SN850X 1TB",
                            Price = 4499m
                        },
                        new
                        {
                            Id = 144,
                            Brand = "WD",
                            CategoryId = 8,
                            Name = "WD Blue SN570 1TB",
                            Price = 2999m
                        },
                        new
                        {
                            Id = 145,
                            Brand = "Kingston",
                            CategoryId = 8,
                            Name = "Kingston NV2 1TB",
                            Price = 2499m
                        },
                        new
                        {
                            Id = 146,
                            Brand = "Kingston",
                            CategoryId = 8,
                            Name = "Kingston KC3000 2TB",
                            Price = 6999m
                        },
                        new
                        {
                            Id = 147,
                            Brand = "Crucial",
                            CategoryId = 8,
                            Name = "Crucial P5 Plus 1TB",
                            Price = 3999m
                        },
                        new
                        {
                            Id = 148,
                            Brand = "Crucial",
                            CategoryId = 8,
                            Name = "Crucial MX500 1TB",
                            Price = 3499m
                        },
                        new
                        {
                            Id = 149,
                            Brand = "ADATA",
                            CategoryId = 8,
                            Name = "ADATA SX8200 Pro 1TB",
                            Price = 3299m
                        },
                        new
                        {
                            Id = 150,
                            Brand = "ADATA",
                            CategoryId = 8,
                            Name = "ADATA Legend 960 2TB",
                            Price = 6499m
                        },
                        new
                        {
                            Id = 151,
                            Brand = "Samsung",
                            CategoryId = 8,
                            Name = "Samsung 870 EVO 1TB",
                            Price = 2999m
                        },
                        new
                        {
                            Id = 152,
                            Brand = "WD",
                            CategoryId = 8,
                            Name = "WD Green 480GB",
                            Price = 1299m
                        },
                        new
                        {
                            Id = 153,
                            Brand = "Kingston",
                            CategoryId = 8,
                            Name = "Kingston A400 480GB",
                            Price = 1199m
                        },
                        new
                        {
                            Id = 154,
                            Brand = "Seagate",
                            CategoryId = 8,
                            Name = "Seagate FireCuda 530 1TB",
                            Price = 5499m
                        },
                        new
                        {
                            Id = 155,
                            Brand = "Samsung",
                            CategoryId = 8,
                            Name = "Samsung 990 Pro 2TB",
                            Price = 8999m
                        },
                        new
                        {
                            Id = 156,
                            Brand = "WD",
                            CategoryId = 8,
                            Name = "WD Black SN770 1TB",
                            Price = 3499m
                        },
                        new
                        {
                            Id = 157,
                            Brand = "Kingston",
                            CategoryId = 8,
                            Name = "Kingston Fury Renegade 1TB",
                            Price = 4299m
                        },
                        new
                        {
                            Id = 158,
                            Brand = "Crucial",
                            CategoryId = 8,
                            Name = "Crucial P3 1TB",
                            Price = 2799m
                        },
                        new
                        {
                            Id = 159,
                            Brand = "ADATA",
                            CategoryId = 8,
                            Name = "ADATA SU650 480GB",
                            Price = 1099m
                        },
                        new
                        {
                            Id = 160,
                            Brand = "Samsung",
                            CategoryId = 8,
                            Name = "Samsung T7 1TB External",
                            Price = 3999m
                        },
                        new
                        {
                            Id = 161,
                            Brand = "Logitech",
                            CategoryId = 9,
                            Name = "MX Master 3S",
                            Price = 3999m
                        },
                        new
                        {
                            Id = 162,
                            Brand = "Logitech",
                            CategoryId = 9,
                            Name = "G Pro X Superlight",
                            Price = 4999m
                        },
                        new
                        {
                            Id = 163,
                            Brand = "Razer",
                            CategoryId = 9,
                            Name = "Razer DeathAdder V3",
                            Price = 3499m
                        },
                        new
                        {
                            Id = 164,
                            Brand = "SteelSeries",
                            CategoryId = 9,
                            Name = "SteelSeries Rival 5",
                            Price = 2499m
                        },
                        new
                        {
                            Id = 165,
                            Brand = "HyperX",
                            CategoryId = 9,
                            Name = "HyperX Alloy Origins",
                            Price = 3999m
                        },
                        new
                        {
                            Id = 166,
                            Brand = "Corsair",
                            CategoryId = 9,
                            Name = "Corsair K70 RGB",
                            Price = 4999m
                        },
                        new
                        {
                            Id = 167,
                            Brand = "Logitech",
                            CategoryId = 9,
                            Name = "Logitech G915",
                            Price = 7999m
                        },
                        new
                        {
                            Id = 168,
                            Brand = "Razer",
                            CategoryId = 9,
                            Name = "Razer BlackWidow V4",
                            Price = 5499m
                        },
                        new
                        {
                            Id = 169,
                            Brand = "SteelSeries",
                            CategoryId = 9,
                            Name = "SteelSeries Apex 7",
                            Price = 4499m
                        },
                        new
                        {
                            Id = 170,
                            Brand = "HyperX",
                            CategoryId = 9,
                            Name = "HyperX Cloud II",
                            Price = 2999m
                        },
                        new
                        {
                            Id = 171,
                            Brand = "Logitech",
                            CategoryId = 9,
                            Name = "Logitech G Pro X Headset",
                            Price = 3999m
                        },
                        new
                        {
                            Id = 172,
                            Brand = "Razer",
                            CategoryId = 9,
                            Name = "Razer Kraken V3",
                            Price = 3499m
                        },
                        new
                        {
                            Id = 173,
                            Brand = "Corsair",
                            CategoryId = 9,
                            Name = "Corsair HS80",
                            Price = 4499m
                        },
                        new
                        {
                            Id = 174,
                            Brand = "Logitech",
                            CategoryId = 9,
                            Name = "Logitech C920 Webcam",
                            Price = 2999m
                        },
                        new
                        {
                            Id = 175,
                            Brand = "Razer",
                            CategoryId = 9,
                            Name = "Razer Kiyo Pro",
                            Price = 5999m
                        },
                        new
                        {
                            Id = 176,
                            Brand = "SteelSeries",
                            CategoryId = 9,
                            Name = "SteelSeries Arctis 7",
                            Price = 4999m
                        },
                        new
                        {
                            Id = 177,
                            Brand = "HyperX",
                            CategoryId = 9,
                            Name = "HyperX Pulsefire Haste",
                            Price = 1999m
                        },
                        new
                        {
                            Id = 178,
                            Brand = "Logitech",
                            CategoryId = 9,
                            Name = "Logitech G502 X",
                            Price = 3299m
                        },
                        new
                        {
                            Id = 179,
                            Brand = "Razer",
                            CategoryId = 9,
                            Name = "Razer Basilisk V3",
                            Price = 2999m
                        },
                        new
                        {
                            Id = 180,
                            Brand = "Corsair",
                            CategoryId = 9,
                            Name = "Corsair MM700 RGB Pad",
                            Price = 1999m
                        },
                        new
                        {
                            Id = 181,
                            Brand = "TP-Link",
                            CategoryId = 10,
                            Name = "Archer AX55",
                            Price = 3499m
                        },
                        new
                        {
                            Id = 182,
                            Brand = "TP-Link",
                            CategoryId = 10,
                            Name = "Archer AX73",
                            Price = 4999m
                        },
                        new
                        {
                            Id = 183,
                            Brand = "TP-Link",
                            CategoryId = 10,
                            Name = "Deco X20",
                            Price = 6999m
                        },
                        new
                        {
                            Id = 184,
                            Brand = "ASUS",
                            CategoryId = 10,
                            Name = "RT-AX86U",
                            Price = 8999m
                        },
                        new
                        {
                            Id = 185,
                            Brand = "ASUS",
                            CategoryId = 10,
                            Name = "RT-AX58U",
                            Price = 4999m
                        },
                        new
                        {
                            Id = 186,
                            Brand = "Netgear",
                            CategoryId = 10,
                            Name = "Nighthawk AX12",
                            Price = 12999m
                        },
                        new
                        {
                            Id = 187,
                            Brand = "Netgear",
                            CategoryId = 10,
                            Name = "Nighthawk R7000",
                            Price = 3999m
                        },
                        new
                        {
                            Id = 188,
                            Brand = "Ubiquiti",
                            CategoryId = 10,
                            Name = "UniFi Dream Router",
                            Price = 7999m
                        },
                        new
                        {
                            Id = 189,
                            Brand = "Ubiquiti",
                            CategoryId = 10,
                            Name = "UniFi AP AC Pro",
                            Price = 5999m
                        },
                        new
                        {
                            Id = 190,
                            Brand = "MikroTik",
                            CategoryId = 10,
                            Name = "MikroTik hAP ax3",
                            Price = 3499m
                        },
                        new
                        {
                            Id = 191,
                            Brand = "MikroTik",
                            CategoryId = 10,
                            Name = "MikroTik RB4011",
                            Price = 7999m
                        },
                        new
                        {
                            Id = 192,
                            Brand = "D-Link",
                            CategoryId = 10,
                            Name = "D-Link DIR-X5460",
                            Price = 3999m
                        },
                        new
                        {
                            Id = 193,
                            Brand = "D-Link",
                            CategoryId = 10,
                            Name = "D-Link DIR-842",
                            Price = 1999m
                        },
                        new
                        {
                            Id = 194,
                            Brand = "TP-Link",
                            CategoryId = 10,
                            Name = "TP-Link TL-SG108 Switch",
                            Price = 999m
                        },
                        new
                        {
                            Id = 195,
                            Brand = "Netgear",
                            CategoryId = 10,
                            Name = "Netgear GS308 Switch",
                            Price = 1299m
                        },
                        new
                        {
                            Id = 196,
                            Brand = "ASUS",
                            CategoryId = 10,
                            Name = "ASUS ZenWiFi XT8",
                            Price = 12999m
                        },
                        new
                        {
                            Id = 197,
                            Brand = "TP-Link",
                            CategoryId = 10,
                            Name = "TP-Link RE650 Extender",
                            Price = 1999m
                        },
                        new
                        {
                            Id = 198,
                            Brand = "Netgear",
                            CategoryId = 10,
                            Name = "Netgear Orbi RBK352",
                            Price = 8999m
                        },
                        new
                        {
                            Id = 199,
                            Brand = "MikroTik",
                            CategoryId = 10,
                            Name = "MikroTik CRS326",
                            Price = 9999m
                        },
                        new
                        {
                            Id = 200,
                            Brand = "Ubiquiti",
                            CategoryId = 10,
                            Name = "Ubiquiti UniFi Switch 8",
                            Price = 6499m
                        });
                });

            modelBuilder.Entity("_01_ASP_MVC_Shop.Models.ProductModel", b =>
                {
                    b.HasOne("_01_ASP_MVC_Shop.Models.CategoryModel", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("_01_ASP_MVC_Shop.Models.CategoryModel", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
