// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _01_ASP_MVC_Shop.Data;

#nullable disable

namespace _01_ASP_MVC_Shop.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("_01_ASP_MVC_Shop.Models.CategoryModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Ноутбуки"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Настільні ПК"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Монітори"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Відеокарти"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Процесори"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Материнські плати"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Оперативна пам’ять"
                        },
                        new
                        {
                            Id = 8,
                            Name = "SSD накопичувачі"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Периферія"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Мережеве обладнання"
                        });
                });

            modelBuilder.Entity("_01_ASP_MVC_Shop.Models.ProductModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "ASUS",
                            CategoryId = 1,
                            Image = "01noutbuki.png",
                            Name = "ROG Strix G16",
                            Price = 58999m
                        },
                        new
                        {
                            Id = 2,
                            Brand = "ASUS",
                            CategoryId = 1,
                            Image = "01noutbuki.png",
                            Name = "TUF Gaming A15",
                            Price = 36999m
                        },
                        new
                        {
                            Id = 3,
                            Brand = "ASUS",
                            CategoryId = 1,
                            Image = "01noutbuki.png",
                            Name = "ZenBook 14",
                            Price = 38999m
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Apple",
                            CategoryId = 1,
                            Image = "01noutbuki.png",
                            Name = "MacBook Air M2",
                            Price = 45999m
                        },
                        new
                        {
                            Id = 5,
                            Brand = "Apple",
                            CategoryId = 1,
                            Image = "01noutbuki.png",
                            Name = "MacBook Pro 14 M3",
                            Price = 89999m
                        },
                        new
                        {
                            Id = 6,
                            Brand = "Lenovo",
                            CategoryId = 1,
                            Image = "01noutbuki.png",
                            Name = "ThinkPad X13",
                            Price = 39999m
                        },
                        new
                        {
                            Id = 7,
                            Brand = "Lenovo",
                            CategoryId = 1,
                            Image = "01noutbuki.png",
                            Name = "Legion 5 Pro",
                            Price = 54999m
                        },
                        new
                        {
                            Id = 8,
                            Brand = "Lenovo",
                            CategoryId = 1,
                            Image = "01noutbuki.png",
                            Name = "IdeaPad 5",
                            Price = 21999m
                        },
                        new
                        {
                            Id = 9,
                            Brand = "Acer",
                            CategoryId = 1,
                            Image = "01noutbuki.png",
                            Name = "Predator Helios 16",
                            Price = 67999m
                        },
                        new
                        {
                            Id = 10,
                            Brand = "Acer",
                            CategoryId = 1,
                            Image = "01noutbuki.png",
                            Name = "Swift X",
                            Price = 32999m
                        },
                        new
                        {
                            Id = 11,
                            Brand = "HP",
                            CategoryId = 1,
                            Image = "01noutbuki.png",
                            Name = "OMEN 16",
                            Price = 55999m
                        },
                        new
                        {
                            Id = 12,
                            Brand = "HP",
                            CategoryId = 1,
                            Image = "01noutbuki.png",
                            Name = "Pavilion 15",
                            Price = 21999m
                        },
                        new
                        {
                            Id = 13,
                            Brand = "Dell",
                            CategoryId = 1,
                            Image = "01noutbuki.png",
                            Name = "XPS 13",
                            Price = 49999m
                        },
                        new
                        {
                            Id = 14,
                            Brand = "Dell",
                            CategoryId = 1,
                            Image = "01noutbuki.png",
                            Name = "Inspiron 15",
                            Price = 23999m
                        },
                        new
                        {
                            Id = 15,
                            Brand = "Microsoft",
                            CategoryId = 1,
                            Image = "01noutbuki.png",
                            Name = "Surface Laptop 5",
                            Price = 57999m
                        },
                        new
                        {
                            Id = 16,
                            Brand = "Samsung",
                            CategoryId = 1,
                            Image = "01noutbuki.png",
                            Name = "Samsung Galaxy Book3",
                            Price = 34999m
                        },
                        new
                        {
                            Id = 17,
                            Brand = "Razer",
                            CategoryId = 1,
                            Image = "01noutbuki.png",
                            Name = "Razer Blade 15",
                            Price = 79999m
                        },
                        new
                        {
                            Id = 18,
                            Brand = "Acer",
                            CategoryId = 1,
                            Image = "01noutbuki.png",
                            Name = "Nitro 5",
                            Price = 27999m
                        },
                        new
                        {
                            Id = 19,
                            Brand = "ASUS",
                            CategoryId = 1,
                            Image = "01noutbuki.png",
                            Name = "VivoBook 15",
                            Price = 19999m
                        },
                        new
                        {
                            Id = 20,
                            Brand = "Dell",
                            CategoryId = 1,
                            Image = "01noutbuki.png",
                            Name = "Latitude 7440",
                            Price = 46999m
                        },
                        new
                        {
                            Id = 21,
                            Brand = "ASUS",
                            CategoryId = 2,
                            Image = "02kompyutery.png",
                            Name = "ROG Strix GT15",
                            Price = 65999m
                        },
                        new
                        {
                            Id = 22,
                            Brand = "HP",
                            CategoryId = 2,
                            Image = "02kompyutery.png",
                            Name = "HP Omen 45L",
                            Price = 89999m
                        },
                        new
                        {
                            Id = 23,
                            Brand = "Acer",
                            CategoryId = 2,
                            Image = "02kompyutery.png",
                            Name = "Acer Predator Orion 3000",
                            Price = 72999m
                        },
                        new
                        {
                            Id = 24,
                            Brand = "Lenovo",
                            CategoryId = 2,
                            Image = "02kompyutery.png",
                            Name = "Lenovo Legion Tower 5",
                            Price = 68999m
                        },
                        new
                        {
                            Id = 25,
                            Brand = "Dell",
                            CategoryId = 2,
                            Image = "02kompyutery.png",
                            Name = "Alienware Aurora R15",
                            Price = 119999m
                        },
                        new
                        {
                            Id = 26,
                            Brand = "MSI",
                            CategoryId = 2,
                            Image = "02kompyutery.png",
                            Name = "MSI Infinite X2",
                            Price = 94999m
                        },
                        new
                        {
                            Id = 27,
                            Brand = "Apple",
                            CategoryId = 2,
                            Image = "02kompyutery.png",
                            Name = "Mac Studio M2",
                            Price = 99999m
                        },
                        new
                        {
                            Id = 28,
                            Brand = "Apple",
                            CategoryId = 2,
                            Image = "02kompyutery.png",
                            Name = "Mac Mini M2",
                            Price = 29999m
                        },
                        new
                        {
                            Id = 29,
                            Brand = "ASUS",
                            CategoryId = 2,
                            Image = "02kompyutery.png",
                            Name = "ExpertCenter D5",
                            Price = 25999m
                        },
                        new
                        {
                            Id = 30,
                            Brand = "HP",
                            CategoryId = 2,
                            Image = "02kompyutery.png",
                            Name = "ProDesk 400",
                            Price = 21999m
                        },
                        new
                        {
                            Id = 31,
                            Brand = "Lenovo",
                            CategoryId = 2,
                            Image = "02kompyutery.png",
                            Name = "ThinkCentre M70",
                            Price = 23999m
                        },
                        new
                        {
                            Id = 32,
                            Brand = "Dell",
                            CategoryId = 2,
                            Image = "02kompyutery.png",
                            Name = "OptiPlex 7000",
                            Price = 28999m
                        },
                        new
                        {
                            Id = 33,
                            Brand = "Acer",
                            CategoryId = 2,
                            Image = "02kompyutery.png",
                            Name = "Aspire TC",
                            Price = 19999m
                        },
                        new
                        {
                            Id = 34,
                            Brand = "Gigabyte",
                            CategoryId = 2,
                            Image = "02kompyutery.png",
                            Name = "AORUS Model X",
                            Price = 109999m
                        },
                        new
                        {
                            Id = 35,
                            Brand = "MSI",
                            CategoryId = 2,
                            Image = "02kompyutery.png",
                            Name = "Trident 3",
                            Price = 49999m
                        },
                        new
                        {
                            Id = 36,
                            Brand = "HP",
                            CategoryId = 2,
                            Image = "02kompyutery.png",
                            Name = "Pavilion Gaming TG01",
                            Price = 37999m
                        },
                        new
                        {
                            Id = 37,
                            Brand = "Lenovo",
                            CategoryId = 2,
                            Image = "02kompyutery.png",
                            Name = "IdeaCentre 5",
                            Price = 31999m
                        },
                        new
                        {
                            Id = 38,
                            Brand = "Dell",
                            CategoryId = 2,
                            Image = "02kompyutery.png",
                            Name = "Vostro 3910",
                            Price = 26999m
                        },
                        new
                        {
                            Id = 39,
                            Brand = "ASUS",
                            CategoryId = 2,
                            Image = "02kompyutery.png",
                            Name = "ROG G22CH",
                            Price = 74999m
                        },
                        new
                        {
                            Id = 40,
                            Brand = "Acer",
                            CategoryId = 2,
                            Image = "02kompyutery.png",
                            Name = "Veriton X",
                            Price = 22999m
                        },
                        new
                        {
                            Id = 41,
                            Brand = "Samsung",
                            CategoryId = 3,
                            Image = "03monitory.png",
                            Name = "Odyssey G7 27",
                            Price = 18999m
                        },
                        new
                        {
                            Id = 42,
                            Brand = "LG",
                            CategoryId = 3,
                            Image = "03monitory.png",
                            Name = "UltraGear 27GP850",
                            Price = 17999m
                        },
                        new
                        {
                            Id = 43,
                            Brand = "ASUS",
                            CategoryId = 3,
                            Image = "03monitory.png",
                            Name = "ProArt PA278",
                            Price = 15999m
                        },
                        new
                        {
                            Id = 44,
                            Brand = "Dell",
                            CategoryId = 3,
                            Image = "03monitory.png",
                            Name = "Dell S2721D",
                            Price = 13999m
                        },
                        new
                        {
                            Id = 45,
                            Brand = "AOC",
                            CategoryId = 3,
                            Image = "03monitory.png",
                            Name = "AOC Q27G2",
                            Price = 12999m
                        },
                        new
                        {
                            Id = 46,
                            Brand = "ViewSonic",
                            CategoryId = 3,
                            Image = "03monitory.png",
                            Name = "ViewSonic VX2758",
                            Price = 11999m
                        },
                        new
                        {
                            Id = 47,
                            Brand = "BenQ",
                            CategoryId = 3,
                            Image = "03monitory.png",
                            Name = "BenQ EX2780Q",
                            Price = 16999m
                        },
                        new
                        {
                            Id = 48,
                            Brand = "Gigabyte",
                            CategoryId = 3,
                            Image = "03monitory.png",
                            Name = "Gigabyte M27Q",
                            Price = 14999m
                        },
                        new
                        {
                            Id = 49,
                            Brand = "Samsung",
                            CategoryId = 3,
                            Image = "03monitory.png",
                            Name = "Odyssey Neo G8",
                            Price = 34999m
                        },
                        new
                        {
                            Id = 50,
                            Brand = "LG",
                            CategoryId = 3,
                            Image = "03monitory.png",
                            Name = "LG 34WN80C",
                            Price = 24999m
                        },
                        new
                        {
                            Id = 51,
                            Brand = "ASUS",
                            CategoryId = 3,
                            Image = "03monitory.png",
                            Name = "ASUS VG259QM",
                            Price = 9999m
                        },
                        new
                        {
                            Id = 52,
                            Brand = "Dell",
                            CategoryId = 3,
                            Image = "03monitory.png",
                            Name = "Dell U2720Q",
                            Price = 19999m
                        },
                        new
                        {
                            Id = 53,
                            Brand = "Philips",
                            CategoryId = 3,
                            Image = "03monitory.png",
                            Name = "Philips 276E",
                            Price = 8999m
                        },
                        new
                        {
                            Id = 54,
                            Brand = "MSI",
                            CategoryId = 3,
                            Image = "03monitory.png",
                            Name = "MSI Optix G241",
                            Price = 7999m
                        },
                        new
                        {
                            Id = 55,
                            Brand = "HP",
                            CategoryId = 3,
                            Image = "03monitory.png",
                            Name = "HP X27",
                            Price = 8999m
                        },
                        new
                        {
                            Id = 56,
                            Brand = "Lenovo",
                            CategoryId = 3,
                            Image = "03monitory.png",
                            Name = "Lenovo G27",
                            Price = 8499m
                        },
                        new
                        {
                            Id = 57,
                            Brand = "Acer",
                            CategoryId = 3,
                            Image = "03monitory.png",
                            Name = "Acer Nitro VG240",
                            Price = 7499m
                        },
                        new
                        {
                            Id = 58,
                            Brand = "Samsung",
                            CategoryId = 3,
                            Image = "03monitory.png",
                            Name = "Samsung S24R350",
                            Price = 5999m
                        },
                        new
                        {
                            Id = 59,
                            Brand = "LG",
                            CategoryId = 3,
                            Image = "03monitory.png",
                            Name = "LG 24MK600",
                            Price = 5499m
                        },
                        new
                        {
                            Id = 60,
                            Brand = "Dell",
                            CategoryId = 3,
                            Image = "03monitory.png",
                            Name = "Dell E2422H",
                            Price = 4999m
                        },
                        new
                        {
                            Id = 61,
                            Brand = "Gigabyte",
                            CategoryId = 4,
                            Image = "04videocarty.jpg",
                            Name = "RTX 4090 Gaming OC",
                            Price = 89999m
                        },
                        new
                        {
                            Id = 62,
                            Brand = "MSI",
                            CategoryId = 4,
                            Image = "04videocarty.jpg",
                            Name = "RTX 4080 SUPRIM",
                            Price = 69999m
                        },
                        new
                        {
                            Id = 63,
                            Brand = "ASUS",
                            CategoryId = 4,
                            Image = "04videocarty.jpg",
                            Name = "RTX 4070 Ti",
                            Price = 49999m
                        },
                        new
                        {
                            Id = 64,
                            Brand = "Gigabyte",
                            CategoryId = 4,
                            Image = "04videocarty.jpg",
                            Name = "RTX 4060",
                            Price = 19999m
                        },
                        new
                        {
                            Id = 65,
                            Brand = "Sapphire",
                            CategoryId = 4,
                            Image = "04videocarty.jpg",
                            Name = "RX 7900 XTX",
                            Price = 57999m
                        },
                        new
                        {
                            Id = 66,
                            Brand = "PowerColor",
                            CategoryId = 4,
                            Image = "04videocarty.jpg",
                            Name = "RX 7800 XT",
                            Price = 34999m
                        },
                        new
                        {
                            Id = 67,
                            Brand = "ASRock",
                            CategoryId = 4,
                            Image = "04videocarty.jpg",
                            Name = "RX 7700 XT",
                            Price = 29999m
                        },
                        new
                        {
                            Id = 68,
                            Brand = "MSI",
                            CategoryId = 4,
                            Image = "04videocarty.jpg",
                            Name = "RTX 3060",
                            Price = 14999m
                        },
                        new
                        {
                            Id = 69,
                            Brand = "ASUS",
                            CategoryId = 4,
                            Image = "04videocarty.jpg",
                            Name = "RTX 3050",
                            Price = 10999m
                        },
                        new
                        {
                            Id = 70,
                            Brand = "Gigabyte",
                            CategoryId = 4,
                            Image = "04videocarty.jpg",
                            Name = "GTX 1660 Super",
                            Price = 9999m
                        },
                        new
                        {
                            Id = 71,
                            Brand = "Sapphire",
                            CategoryId = 4,
                            Image = "04videocarty.jpg",
                            Name = "RX 6600",
                            Price = 11999m
                        },
                        new
                        {
                            Id = 72,
                            Brand = "PowerColor",
                            CategoryId = 4,
                            Image = "04videocarty.jpg",
                            Name = "RX 6500 XT",
                            Price = 8999m
                        },
                        new
                        {
                            Id = 73,
                            Brand = "EVGA",
                            CategoryId = 4,
                            Image = "04videocarty.jpg",
                            Name = "RTX 3080",
                            Price = 32999m
                        },
                        new
                        {
                            Id = 74,
                            Brand = "Zotac",
                            CategoryId = 4,
                            Image = "04videocarty.jpg",
                            Name = "RTX 3070",
                            Price = 24999m
                        },
                        new
                        {
                            Id = 75,
                            Brand = "MSI",
                            CategoryId = 4,
                            Image = "04videocarty.jpg",
                            Name = "RTX 2060",
                            Price = 12999m
                        },
                        new
                        {
                            Id = 76,
                            Brand = "Sapphire",
                            CategoryId = 4,
                            Image = "04videocarty.jpg",
                            Name = "RX 5700 XT",
                            Price = 13999m
                        },
                        new
                        {
                            Id = 77,
                            Brand = "NVIDIA",
                            CategoryId = 4,
                            Image = "04videocarty.jpg",
                            Name = "RTX 4050 Laptop GPU",
                            Price = 9999m
                        },
                        new
                        {
                            Id = 78,
                            Brand = "PNY",
                            CategoryId = 4,
                            Image = "04videocarty.jpg",
                            Name = "RTX 5000 Ada",
                            Price = 109999m
                        },
                        new
                        {
                            Id = 79,
                            Brand = "NVIDIA",
                            CategoryId = 4,
                            Image = "04videocarty.jpg",
                            Name = "A2000",
                            Price = 25999m
                        },
                        new
                        {
                            Id = 80,
                            Brand = "ASRock",
                            CategoryId = 4,
                            Image = "04videocarty.jpg",
                            Name = "RX 6400",
                            Price = 7999m
                        },
                        new
                        {
                            Id = 81,
                            Brand = "AMD",
                            CategoryId = 5,
                            Image = "05prozesory.jpg",
                            Name = "Ryzen 9 7950X",
                            Price = 25999m
                        },
                        new
                        {
                            Id = 82,
                            Brand = "AMD",
                            CategoryId = 5,
                            Image = "05prozesory.jpg",
                            Name = "Ryzen 7 7800X3D",
                            Price = 18999m
                        },
                        new
                        {
                            Id = 83,
                            Brand = "AMD",
                            CategoryId = 5,
                            Image = "05prozesory.jpg",
                            Name = "Ryzen 5 7600X",
                            Price = 11999m
                        },
                        new
                        {
                            Id = 84,
                            Brand = "AMD",
                            CategoryId = 5,
                            Image = "05prozesory.jpg",
                            Name = "Ryzen 5 5600",
                            Price = 6999m
                        },
                        new
                        {
                            Id = 85,
                            Brand = "Intel",
                            CategoryId = 5,
                            Image = "05prozesory.jpg",
                            Name = "Core i9-14900K",
                            Price = 27999m
                        },
                        new
                        {
                            Id = 86,
                            Brand = "Intel",
                            CategoryId = 5,
                            Image = "05prozesory.jpg",
                            Name = "Core i7-14700K",
                            Price = 19999m
                        },
                        new
                        {
                            Id = 87,
                            Brand = "Intel",
                            CategoryId = 5,
                            Image = "05prozesory.jpg",
                            Name = "Core i5-14600K",
                            Price = 14999m
                        },
                        new
                        {
                            Id = 88,
                            Brand = "Intel",
                            CategoryId = 5,
                            Image = "05prozesory.jpg",
                            Name = "Core i5-13400",
                            Price = 9999m
                        },
                        new
                        {
                            Id = 89,
                            Brand = "Intel",
                            CategoryId = 5,
                            Image = "05prozesory.jpg",
                            Name = "Core i3-13100",
                            Price = 5999m
                        },
                        new
                        {
                            Id = 90,
                            Brand = "AMD",
                            CategoryId = 5,
                            Image = "05prozesory.jpg",
                            Name = "Ryzen 9 5900X",
                            Price = 17999m
                        },
                        new
                        {
                            Id = 91,
                            Brand = "AMD",
                            CategoryId = 5,
                            Image = "05prozesory.jpg",
                            Name = "Ryzen 7 5700X",
                            Price = 10999m
                        },
                        new
                        {
                            Id = 92,
                            Brand = "AMD",
                            CategoryId = 5,
                            Image = "05prozesory.jpg",
                            Name = "Ryzen 5 5500",
                            Price = 4999m
                        },
                        new
                        {
                            Id = 93,
                            Brand = "Intel",
                            CategoryId = 5,
                            Image = "05prozesory.jpg",
                            Name = "Xeon W-1370",
                            Price = 22999m
                        },
                        new
                        {
                            Id = 94,
                            Brand = "AMD",
                            CategoryId = 5,
                            Image = "05prozesory.jpg",
                            Name = "Threadripper 7970X",
                            Price = 99999m
                        },
                        new
                        {
                            Id = 95,
                            Brand = "Intel",
                            CategoryId = 5,
                            Image = "05prozesory.jpg",
                            Name = "Core Ultra 7",
                            Price = 18999m
                        },
                        new
                        {
                            Id = 96,
                            Brand = "Intel",
                            CategoryId = 5,
                            Image = "05prozesory.jpg",
                            Name = "Core Ultra 5",
                            Price = 13999m
                        },
                        new
                        {
                            Id = 97,
                            Brand = "AMD",
                            CategoryId = 5,
                            Image = "05prozesory.jpg",
                            Name = "Athlon 3000G",
                            Price = 1999m
                        },
                        new
                        {
                            Id = 98,
                            Brand = "Intel",
                            CategoryId = 5,
                            Image = "05prozesory.jpg",
                            Name = "Pentium Gold",
                            Price = 2999m
                        },
                        new
                        {
                            Id = 99,
                            Brand = "AMD",
                            CategoryId = 5,
                            Image = "05prozesory.jpg",
                            Name = "Ryzen 3 4100",
                            Price = 3999m
                        },
                        new
                        {
                            Id = 100,
                            Brand = "Intel",
                            CategoryId = 5,
                            Image = "05prozesory.jpg",
                            Name = "Core i9-13900KS",
                            Price = 29999m
                        },
                        new
                        {
                            Id = 101,
                            Brand = "ASUS",
                            CategoryId = 6,
                            Image = "06materinskykarty.jpg",
                            Name = "ROG Strix Z790-E",
                            Price = 18999m
                        },
                        new
                        {
                            Id = 102,
                            Brand = "MSI",
                            CategoryId = 6,
                            Image = "06materinskykarty.jpg",
                            Name = "MSI MPG Z790 Carbon",
                            Price = 17999m
                        },
                        new
                        {
                            Id = 103,
                            Brand = "Gigabyte",
                            CategoryId = 6,
                            Image = "06materinskykarty.jpg",
                            Name = "Gigabyte Z790 AORUS Elite",
                            Price = 15999m
                        },
                        new
                        {
                            Id = 104,
                            Brand = "ASRock",
                            CategoryId = 6,
                            Image = "06materinskykarty.jpg",
                            Name = "ASRock Z790 Steel Legend",
                            Price = 13999m
                        },
                        new
                        {
                            Id = 105,
                            Brand = "ASUS",
                            CategoryId = 6,
                            Image = "06materinskykarty.jpg",
                            Name = "ASUS B650-PLUS",
                            Price = 9999m
                        },
                        new
                        {
                            Id = 106,
                            Brand = "MSI",
                            CategoryId = 6,
                            Image = "06materinskykarty.jpg",
                            Name = "MSI B650 Tomahawk",
                            Price = 10999m
                        },
                        new
                        {
                            Id = 107,
                            Brand = "Gigabyte",
                            CategoryId = 6,
                            Image = "06materinskykarty.jpg",
                            Name = "Gigabyte B550M DS3H",
                            Price = 4999m
                        },
                        new
                        {
                            Id = 108,
                            Brand = "ASUS",
                            CategoryId = 6,
                            Image = "06materinskykarty.jpg",
                            Name = "ASUS Prime H610M",
                            Price = 3999m
                        },
                        new
                        {
                            Id = 109,
                            Brand = "MSI",
                            CategoryId = 6,
                            Image = "06materinskykarty.jpg",
                            Name = "MSI PRO H610",
                            Price = 3499m
                        },
                        new
                        {
                            Id = 110,
                            Brand = "ASRock",
                            CategoryId = 6,
                            Image = "06materinskykarty.jpg",
                            Name = "ASRock B450 Pro4",
                            Price = 2999m
                        },
                        new
                        {
                            Id = 111,
                            Brand = "ASUS",
                            CategoryId = 6,
                            Image = "06materinskykarty.jpg",
                            Name = "ROG Crosshair X670E",
                            Price = 24999m
                        },
                        new
                        {
                            Id = 112,
                            Brand = "MSI",
                            CategoryId = 6,
                            Image = "06materinskykarty.jpg",
                            Name = "MSI MEG X670E Ace",
                            Price = 27999m
                        },
                        new
                        {
                            Id = 113,
                            Brand = "Gigabyte",
                            CategoryId = 6,
                            Image = "06materinskykarty.jpg",
                            Name = "Gigabyte X670 AORUS Master",
                            Price = 23999m
                        },
                        new
                        {
                            Id = 114,
                            Brand = "ASUS",
                            CategoryId = 6,
                            Image = "06materinskykarty.jpg",
                            Name = "ASUS TUF B760M",
                            Price = 8999m
                        },
                        new
                        {
                            Id = 115,
                            Brand = "MSI",
                            CategoryId = 6,
                            Image = "06materinskykarty.jpg",
                            Name = "MSI B760 Gaming Plus",
                            Price = 9499m
                        },
                        new
                        {
                            Id = 116,
                            Brand = "Gigabyte",
                            CategoryId = 6,
                            Image = "06materinskykarty.jpg",
                            Name = "Gigabyte H510M",
                            Price = 2999m
                        },
                        new
                        {
                            Id = 117,
                            Brand = "ASRock",
                            CategoryId = 6,
                            Image = "06materinskykarty.jpg",
                            Name = "ASRock H470 Steel Legend",
                            Price = 3999m
                        },
                        new
                        {
                            Id = 118,
                            Brand = "ASUS",
                            CategoryId = 6,
                            Image = "06materinskykarty.jpg",
                            Name = "ROG Strix B550-F",
                            Price = 7999m
                        },
                        new
                        {
                            Id = 119,
                            Brand = "MSI",
                            CategoryId = 6,
                            Image = "06materinskykarty.jpg",
                            Name = "MSI B550 Gaming Edge",
                            Price = 7499m
                        },
                        new
                        {
                            Id = 120,
                            Brand = "Gigabyte",
                            CategoryId = 6,
                            Image = "06materinskykarty.jpg",
                            Name = "Gigabyte B760 AORUS Elite",
                            Price = 10999m
                        },
                        new
                        {
                            Id = 121,
                            Brand = "Kingston",
                            CategoryId = 7,
                            Image = "07operatyvnapamiat.jpg",
                            Name = "Kingston Fury 16GB DDR5",
                            Price = 3499m
                        },
                        new
                        {
                            Id = 122,
                            Brand = "Corsair",
                            CategoryId = 7,
                            Image = "07operatyvnapamiat.jpg",
                            Name = "Corsair Vengeance 32GB DDR5",
                            Price = 6999m
                        },
                        new
                        {
                            Id = 123,
                            Brand = "G.Skill",
                            CategoryId = 7,
                            Image = "07operatyvnapamiat.jpg",
                            Name = "G.Skill Trident Z 32GB",
                            Price = 7499m
                        },
                        new
                        {
                            Id = 124,
                            Brand = "Kingston",
                            CategoryId = 7,
                            Image = "07operatyvnapamiat.jpg",
                            Name = "Kingston Fury 8GB DDR4",
                            Price = 999m
                        },
                        new
                        {
                            Id = 125,
                            Brand = "Crucial",
                            CategoryId = 7,
                            Image = "07operatyvnapamiat.jpg",
                            Name = "Crucial 16GB DDR4",
                            Price = 1999m
                        },
                        new
                        {
                            Id = 126,
                            Brand = "ADATA",
                            CategoryId = 7,
                            Image = "07operatyvnapamiat.jpg",
                            Name = "ADATA XPG 16GB",
                            Price = 1799m
                        },
                        new
                        {
                            Id = 127,
                            Brand = "TeamGroup",
                            CategoryId = 7,
                            Image = "07operatyvnapamiat.jpg",
                            Name = "TeamGroup T-Force 32GB",
                            Price = 6499m
                        },
                        new
                        {
                            Id = 128,
                            Brand = "Patriot",
                            CategoryId = 7,
                            Image = "07operatyvnapamiat.jpg",
                            Name = "Patriot Viper 16GB",
                            Price = 1999m
                        },
                        new
                        {
                            Id = 129,
                            Brand = "Corsair",
                            CategoryId = 7,
                            Image = "07operatyvnapamiat.jpg",
                            Name = "Corsair Dominator 64GB",
                            Price = 14999m
                        },
                        new
                        {
                            Id = 130,
                            Brand = "G.Skill",
                            CategoryId = 7,
                            Image = "07operatyvnapamiat.jpg",
                            Name = "G.Skill Ripjaws 16GB",
                            Price = 1899m
                        },
                        new
                        {
                            Id = 131,
                            Brand = "Kingston",
                            CategoryId = 7,
                            Image = "07operatyvnapamiat.jpg",
                            Name = "Kingston Fury 32GB",
                            Price = 5999m
                        },
                        new
                        {
                            Id = 132,
                            Brand = "Crucial",
                            CategoryId = 7,
                            Image = "07operatyvnapamiat.jpg",
                            Name = "Crucial 32GB DDR5",
                            Price = 7999m
                        },
                        new
                        {
                            Id = 133,
                            Brand = "ADATA",
                            CategoryId = 7,
                            Image = "07operatyvnapamiat.jpg",
                            Name = "ADATA XPG 32GB",
                            Price = 7499m
                        },
                        new
                        {
                            Id = 134,
                            Brand = "TeamGroup",
                            CategoryId = 7,
                            Image = "07operatyvnapamiat.jpg",
                            Name = "TeamGroup Elite 16GB",
                            Price = 1799m
                        },
                        new
                        {
                            Id = 135,
                            Brand = "Patriot",
                            CategoryId = 7,
                            Image = "07operatyvnapamiat.jpg",
                            Name = "Patriot Signature 8GB",
                            Price = 899m
                        },
                        new
                        {
                            Id = 136,
                            Brand = "Corsair",
                            CategoryId = 7,
                            Image = "07operatyvnapamiat.jpg",
                            Name = "Corsair LPX 16GB",
                            Price = 1999m
                        },
                        new
                        {
                            Id = 137,
                            Brand = "G.Skill",
                            CategoryId = 7,
                            Image = "07operatyvnapamiat.jpg",
                            Name = "G.Skill 8GB DDR4",
                            Price = 899m
                        },
                        new
                        {
                            Id = 138,
                            Brand = "Kingston",
                            CategoryId = 7,
                            Image = "07operatyvnapamiat.jpg",
                            Name = "Kingston Server RAM",
                            Price = 4999m
                        },
                        new
                        {
                            Id = 139,
                            Brand = "Micron",
                            CategoryId = 7,
                            Image = "07operatyvnapamiat.jpg",
                            Name = "Micron ECC 32GB",
                            Price = 8999m
                        },
                        new
                        {
                            Id = 140,
                            Brand = "Samsung",
                            CategoryId = 7,
                            Image = "07operatyvnapamiat.jpg",
                            Name = "Samsung DDR5 16GB",
                            Price = 3499m
                        },
                        new
                        {
                            Id = 141,
                            Brand = "Samsung",
                            CategoryId = 8,
                            Image = "08ssd.jpg",
                            Name = "Samsung 990 Pro 1TB",
                            Price = 4999m
                        },
                        new
                        {
                            Id = 142,
                            Brand = "WD",
                            CategoryId = 8,
                            Image = "08ssd.jpg",
                            Name = "WD Black SN850X",
                            Price = 4799m
                        },
                        new
                        {
                            Id = 143,
                            Brand = "Kingston",
                            CategoryId = 8,
                            Image = "08ssd.jpg",
                            Name = "Kingston KC3000",
                            Price = 4599m
                        },
                        new
                        {
                            Id = 144,
                            Brand = "Crucial",
                            CategoryId = 8,
                            Image = "08ssd.jpg",
                            Name = "Crucial P5 Plus",
                            Price = 3999m
                        },
                        new
                        {
                            Id = 145,
                            Brand = "ADATA",
                            CategoryId = 8,
                            Image = "08ssd.jpg",
                            Name = "ADATA Legend 960",
                            Price = 3799m
                        },
                        new
                        {
                            Id = 146,
                            Brand = "Samsung",
                            CategoryId = 8,
                            Image = "08ssd.jpg",
                            Name = "Samsung 970 EVO",
                            Price = 2999m
                        },
                        new
                        {
                            Id = 147,
                            Brand = "WD",
                            CategoryId = 8,
                            Image = "08ssd.jpg",
                            Name = "WD Blue SN570",
                            Price = 2499m
                        },
                        new
                        {
                            Id = 148,
                            Brand = "Kingston",
                            CategoryId = 8,
                            Image = "08ssd.jpg",
                            Name = "Kingston NV2",
                            Price = 1999m
                        },
                        new
                        {
                            Id = 149,
                            Brand = "Crucial",
                            CategoryId = 8,
                            Image = "08ssd.jpg",
                            Name = "Crucial BX500",
                            Price = 1499m
                        },
                        new
                        {
                            Id = 150,
                            Brand = "Samsung",
                            CategoryId = 8,
                            Image = "08ssd.jpg",
                            Name = "Samsung 870 QVO",
                            Price = 2299m
                        },
                        new
                        {
                            Id = 151,
                            Brand = "WD",
                            CategoryId = 8,
                            Image = "08ssd.jpg",
                            Name = "WD Green SSD",
                            Price = 1199m
                        },
                        new
                        {
                            Id = 152,
                            Brand = "ADATA",
                            CategoryId = 8,
                            Image = "08ssd.jpg",
                            Name = "ADATA SU800",
                            Price = 1399m
                        },
                        new
                        {
                            Id = 153,
                            Brand = "Kingston",
                            CategoryId = 8,
                            Image = "08ssd.jpg",
                            Name = "Kingston A400",
                            Price = 999m
                        },
                        new
                        {
                            Id = 154,
                            Brand = "Samsung",
                            CategoryId = 8,
                            Image = "08ssd.jpg",
                            Name = "Samsung T7 Portable",
                            Price = 3999m
                        },
                        new
                        {
                            Id = 155,
                            Brand = "WD",
                            CategoryId = 8,
                            Image = "08ssd.jpg",
                            Name = "WD My Passport SSD",
                            Price = 3799m
                        },
                        new
                        {
                            Id = 156,
                            Brand = "Crucial",
                            CategoryId = 8,
                            Image = "08ssd.jpg",
                            Name = "Crucial X8 Portable",
                            Price = 3599m
                        },
                        new
                        {
                            Id = 157,
                            Brand = "Seagate",
                            CategoryId = 8,
                            Image = "08ssd.jpg",
                            Name = "Seagate FireCuda 530",
                            Price = 5499m
                        },
                        new
                        {
                            Id = 158,
                            Brand = "PNY",
                            CategoryId = 8,
                            Image = "08ssd.jpg",
                            Name = "PNY CS3140",
                            Price = 4899m
                        },
                        new
                        {
                            Id = 159,
                            Brand = "TeamGroup",
                            CategoryId = 8,
                            Image = "08ssd.jpg",
                            Name = "TeamGroup MP44",
                            Price = 4299m
                        },
                        new
                        {
                            Id = 160,
                            Brand = "Gigabyte",
                            CategoryId = 8,
                            Image = "08ssd.jpg",
                            Name = "Gigabyte AORUS Gen4",
                            Price = 4599m
                        },
                        new
                        {
                            Id = 161,
                            Brand = "Logitech",
                            CategoryId = 9,
                            Image = "09peryfyria.jpg",
                            Name = "MX Master 3S",
                            Price = 3999m
                        },
                        new
                        {
                            Id = 162,
                            Brand = "Logitech",
                            CategoryId = 9,
                            Image = "09peryfyria.jpg",
                            Name = "G Pro Wireless",
                            Price = 4999m
                        },
                        new
                        {
                            Id = 163,
                            Brand = "Razer",
                            CategoryId = 9,
                            Image = "09peryfyria.jpg",
                            Name = "Razer DeathAdder V3",
                            Price = 3499m
                        },
                        new
                        {
                            Id = 164,
                            Brand = "SteelSeries",
                            CategoryId = 9,
                            Image = "09peryfyria.jpg",
                            Name = "SteelSeries Rival 5",
                            Price = 2999m
                        },
                        new
                        {
                            Id = 165,
                            Brand = "Corsair",
                            CategoryId = 9,
                            Image = "09peryfyria.jpg",
                            Name = "Corsair K95 RGB",
                            Price = 6999m
                        },
                        new
                        {
                            Id = 166,
                            Brand = "Logitech",
                            CategoryId = 9,
                            Image = "09peryfyria.jpg",
                            Name = "Logitech G915",
                            Price = 7999m
                        },
                        new
                        {
                            Id = 167,
                            Brand = "Razer",
                            CategoryId = 9,
                            Image = "09peryfyria.jpg",
                            Name = "Razer BlackWidow",
                            Price = 5999m
                        },
                        new
                        {
                            Id = 168,
                            Brand = "HyperX",
                            CategoryId = 9,
                            Image = "09peryfyria.jpg",
                            Name = "HyperX Alloy Core",
                            Price = 2499m
                        },
                        new
                        {
                            Id = 169,
                            Brand = "Logitech",
                            CategoryId = 9,
                            Image = "09peryfyria.jpg",
                            Name = "Logitech C920",
                            Price = 2999m
                        },
                        new
                        {
                            Id = 170,
                            Brand = "Razer",
                            CategoryId = 9,
                            Image = "09peryfyria.jpg",
                            Name = "Razer Kiyo",
                            Price = 3499m
                        },
                        new
                        {
                            Id = 171,
                            Brand = "Blue",
                            CategoryId = 9,
                            Image = "09peryfyria.jpg",
                            Name = "Blue Yeti Mic",
                            Price = 4999m
                        },
                        new
                        {
                            Id = 172,
                            Brand = "HyperX",
                            CategoryId = 9,
                            Image = "09peryfyria.jpg",
                            Name = "HyperX Cloud II",
                            Price = 3999m
                        },
                        new
                        {
                            Id = 173,
                            Brand = "SteelSeries",
                            CategoryId = 9,
                            Image = "09peryfyria.jpg",
                            Name = "SteelSeries Arctis 7",
                            Price = 4999m
                        },
                        new
                        {
                            Id = 174,
                            Brand = "Logitech",
                            CategoryId = 9,
                            Image = "09peryfyria.jpg",
                            Name = "Logitech Z623",
                            Price = 5999m
                        },
                        new
                        {
                            Id = 175,
                            Brand = "Creative",
                            CategoryId = 9,
                            Image = "09peryfyria.jpg",
                            Name = "Creative Pebble",
                            Price = 1999m
                        },
                        new
                        {
                            Id = 176,
                            Brand = "TP-Link",
                            CategoryId = 9,
                            Image = "09peryfyria.jpg",
                            Name = "TP-Link USB Adapter",
                            Price = 799m
                        },
                        new
                        {
                            Id = 177,
                            Brand = "Logitech",
                            CategoryId = 9,
                            Image = "09peryfyria.jpg",
                            Name = "Logitech Mouse Pad",
                            Price = 499m
                        },
                        new
                        {
                            Id = 178,
                            Brand = "Razer",
                            CategoryId = 9,
                            Image = "09peryfyria.jpg",
                            Name = "Razer Mouse Bungee",
                            Price = 999m
                        },
                        new
                        {
                            Id = 179,
                            Brand = "Elgato",
                            CategoryId = 9,
                            Image = "09peryfyria.jpg",
                            Name = "Elgato Stream Deck",
                            Price = 5999m
                        },
                        new
                        {
                            Id = 180,
                            Brand = "Logitech",
                            CategoryId = 9,
                            Image = "09peryfyria.jpg",
                            Name = "Logitech Brio",
                            Price = 6999m
                        },
                        new
                        {
                            Id = 181,
                            Brand = "TP-Link",
                            CategoryId = 10,
                            Image = "10meregeve.png",
                            Name = "Archer AX55",
                            Price = 3499m
                        },
                        new
                        {
                            Id = 182,
                            Brand = "TP-Link",
                            CategoryId = 10,
                            Image = "10meregeve.png",
                            Name = "Archer AX73",
                            Price = 4999m
                        },
                        new
                        {
                            Id = 183,
                            Brand = "TP-Link",
                            CategoryId = 10,
                            Image = "10meregeve.png",
                            Name = "Archer C6",
                            Price = 1999m
                        },
                        new
                        {
                            Id = 184,
                            Brand = "TP-Link",
                            CategoryId = 10,
                            Image = "10meregeve.png",
                            Name = "Deco X20",
                            Price = 6999m
                        },
                        new
                        {
                            Id = 185,
                            Brand = "ASUS",
                            CategoryId = 10,
                            Image = "10meregeve.png",
                            Name = "ASUS RT-AX58U",
                            Price = 3999m
                        },
                        new
                        {
                            Id = 186,
                            Brand = "ASUS",
                            CategoryId = 10,
                            Image = "10meregeve.png",
                            Name = "ASUS RT-AX88U",
                            Price = 7999m
                        },
                        new
                        {
                            Id = 187,
                            Brand = "Netgear",
                            CategoryId = 10,
                            Image = "10meregeve.png",
                            Name = "Netgear Nighthawk",
                            Price = 6999m
                        },
                        new
                        {
                            Id = 188,
                            Brand = "Ubiquiti",
                            CategoryId = 10,
                            Image = "10meregeve.png",
                            Name = "Ubiquiti UniFi AP",
                            Price = 5999m
                        },
                        new
                        {
                            Id = 189,
                            Brand = "TP-Link",
                            CategoryId = 10,
                            Image = "10meregeve.png",
                            Name = "TP-Link Switch 8p",
                            Price = 999m
                        },
                        new
                        {
                            Id = 190,
                            Brand = "TP-Link",
                            CategoryId = 10,
                            Image = "10meregeve.png",
                            Name = "TP-Link Switch 16p",
                            Price = 1999m
                        },
                        new
                        {
                            Id = 191,
                            Brand = "D-Link",
                            CategoryId = 10,
                            Image = "10meregeve.png",
                            Name = "D-Link DIR-825",
                            Price = 1499m
                        },
                        new
                        {
                            Id = 192,
                            Brand = "MikroTik",
                            CategoryId = 10,
                            Image = "10meregeve.png",
                            Name = "MikroTik hAP ac2",
                            Price = 2499m
                        },
                        new
                        {
                            Id = 193,
                            Brand = "MikroTik",
                            CategoryId = 10,
                            Image = "10meregeve.png",
                            Name = "MikroTik RB4011",
                            Price = 7999m
                        },
                        new
                        {
                            Id = 194,
                            Brand = "TP-Link",
                            CategoryId = 10,
                            Image = "10meregeve.png",
                            Name = "TP-Link Range Extender",
                            Price = 999m
                        },
                        new
                        {
                            Id = 195,
                            Brand = "ASUS",
                            CategoryId = 10,
                            Image = "10meregeve.png",
                            Name = "ASUS Mesh Node",
                            Price = 2999m
                        },
                        new
                        {
                            Id = 196,
                            Brand = "Netgear",
                            CategoryId = 10,
                            Image = "10meregeve.png",
                            Name = "Netgear Switch 24p",
                            Price = 4999m
                        },
                        new
                        {
                            Id = 197,
                            Brand = "Ubiquiti",
                            CategoryId = 10,
                            Image = "10meregeve.png",
                            Name = "Ubiquiti Switch Lite",
                            Price = 3999m
                        },
                        new
                        {
                            Id = 198,
                            Brand = "TP-Link",
                            CategoryId = 10,
                            Image = "10meregeve.png",
                            Name = "TP-Link LTE Router",
                            Price = 3499m
                        },
                        new
                        {
                            Id = 199,
                            Brand = "Huawei",
                            CategoryId = 10,
                            Image = "10meregeve.png",
                            Name = "Huawei B535",
                            Price = 2999m
                        },
                        new
                        {
                            Id = 200,
                            Brand = "Zyxel",
                            CategoryId = 10,
                            Image = "10meregeve.png",
                            Name = "Zyxel Armor G5",
                            Price = 8999m
                        });
                });

            modelBuilder.Entity("_01_ASP_MVC_Shop.Models.ProductModel", b =>
                {
                    b.HasOne("_01_ASP_MVC_Shop.Models.CategoryModel", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("_01_ASP_MVC_Shop.Models.CategoryModel", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
